language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  - ANALYZER=""
  - ANALYZER="scan-build -k --status-bugs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      --no-install-recommends
      asciidoc
      clang
      libjson-glib-dev
      lynx
      xsltproc
      xmlto

install:
  - git clone https://github.com/bitlbee/bitlbee
  - cd bitlbee
  - git checkout -b develop origin/develop
  - ./configure
      --events=glib
      --ssl=gnutls
      --debug=1
      --plugins=1
      --jabber=0
      --msn=0
      --oscar=0
      --otr=0
      --purple=0
      --skype=0
      --twitter=0
      --yahoo=0
  - make
  - sudo make install install-dev
  - cd -

script:
  - CFLAGS="-Werror" ./autogen.sh --enable-warnings
  - ${ANALYZER} make
