language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  global:
    - secure: "RyCpkq3KU8zftQfD54rNERzzygzLfJtQQXG13LnsIj3NSx5Attr6aM1lZKLWEEgjpkiEuhXkmcwmOuQJfEqYHxYQ24SSKihE9AvEBrOGNuY8CB4SFZEs+atRgovi2SrttdVOU3AzlZSgUUAaHNBUaC7QgimODAyCPV9KfuQkJEw="
    - COVERITY_SCAN_PROJECT_NAME=jgeboski/bitlbee-facebook
    - COVERITY_SCAN_NOTIFICATION_EMAIL=nope
    - COVERITY_SCAN_BUILD_COMMAND=make
    - COVERITY_SCAN_BRANCH_PATTERN=coverity_scan

  matrix:
    - ANALYZER=""
    - ANALYZER="scan-build -k --status-bugs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      --no-install-recommends
      asciidoc
      clang
      libjson-glib-dev
      lynx
      xsltproc
      xmlto

install:
  - git clone https://github.com/bitlbee/bitlbee
  - cd bitlbee
  - git checkout -b develop origin/develop
  - ./configure
      --events=glib
      --ssl=gnutls
      --debug=1
      --plugins=1
      --jabber=0
      --msn=0
      --oscar=0
      --otr=0
      --purple=0
      --skype=0
      --twitter=0
      --yahoo=0
  - make
  - sudo make install install-dev
  - cd -

script:
  - CFLAGS="-Werror" ./autogen.sh --enable-warnings
  - |
    if [[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]]; then
        curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true
    fi
  - ${ANALYZER} make
