language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  global:
    - secure: "RyCpkq3KU8zftQfD54rNERzzygzLfJtQQXG13LnsIj3NSx5Attr6aM1lZKLWEEgjpkiEuhXkmcwmOuQJfEqYHxYQ24SSKihE9AvEBrOGNuY8CB4SFZEs+atRgovi2SrttdVOU3AzlZSgUUAaHNBUaC7QgimODAyCPV9KfuQkJEw="

  matrix:
    - ANALYZER=""
    - ANALYZER="scan-build -k --status-bugs"

addons:
  coverity_scan:
    project:
      name: jgeboski/bitlbee-facebook
      version: git
      description: bitlbee-facebook

    build_command_prepend: ./autogen.sh
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      --no-install-recommends
      asciidoc
      clang
      libjson-glib-dev
      lynx
      xsltproc
      xmlto

install:
  - git clone https://github.com/bitlbee/bitlbee
  - cd bitlbee
  - git checkout -b develop origin/develop
  - ./configure
      --events=glib
      --ssl=gnutls
      --debug=1
      --plugins=1
      --jabber=0
      --msn=0
      --oscar=0
      --otr=0
      --purple=0
      --skype=0
      --twitter=0
      --yahoo=0
  - make
  - sudo make install install-dev
  - cd -

script:
  - |
    if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then
      CFLAGS="-Werror" ./autogen.sh --enable-warnings
    fi
  - |
    if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then
      ${ANALYZER} make
    fi
